"""rename vibration_on to vibration_type

Revision ID: 7e372e273220
Revises: 4187ec8c71c2
Create Date: 2026-04-27 11:15:39.248189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e372e273220'
down_revision: Union[str, None] = '4187ec8c71c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subtitles_id', table_name='subtitles')
    op.drop_index('ix_subtitles_user_id', table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index('ix_sound_events_device_id', table_name='sound_events')
    op.drop_index('ix_sound_events_id', table_name='sound_events')
    op.drop_index('ix_sound_events_sound_type', table_name='sound_events')
    op.drop_table('sound_events')
    op.add_column('settings', sa.Column('vibration_type', sa.String(length=10), nullable=False, server_default='SINGLE'))
    op.drop_column('settings', 'vibration_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('vibration_on', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('settings', 'vibration_type')
    op.create_table('sound_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sound_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_risk', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stt_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sound_events_pkey')
    )
    op.create_index('ix_sound_events_sound_type', 'sound_events', ['sound_type'], unique=False)
    op.create_index('ix_sound_events_id', 'sound_events', ['id'], unique=False)
    op.create_index('ix_sound_events_device_id', 'sound_events', ['device_id'], unique=False)
    op.create_table('subtitles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subtitles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subtitles_pkey')
    )
    op.create_index('ix_subtitles_user_id', 'subtitles', ['user_id'], unique=False)
    op.create_index('ix_subtitles_id', 'subtitles', ['id'], unique=False)
    # ### end Alembic commands ###
