"""add index to directions created_at

Revision ID: 862389ad37a1
Revises: 7e372e273220
Create Date: 2026-04-27 12:37:04.206983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862389ad37a1'
down_revision: Union[str, None] = '7e372e273220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_directions_created_at'), 'directions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directions_created_at'), table_name='directions')
    # ### end Alembic commands ###
